{{- if and (eq .Values.persistence.volume.type "pvc") (not .Values.persistence.volume.pvc.existingClaim) (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvs-shared-vol
  labels:
    {{- include "generative-virtual-screening-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.volume.pvc.accessMode | default .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.volume.pvc.storageClass | default .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.volume.pvc.size | default .Values.persistence.size | quote }}
{{- end }}
